INDEX = 'index'
TIMESTAMP = 'timestamp'
TRANSACTIONS = 'transactions'
PROOF = 'proof'
PREV_HASH = 'prev_hash'
SENDER = 'sender'
RECIPIENT = 'recipient'
TOTAL = 'total'
MESSAGE = 'message'
BLOCK_CHAIN = 'block_chain'
CHAIN_LENGTH = 'chain_length'
NODES = 'nodes'
LIST_NODES = 'list_nodes'
NEW_CHAIN = 'new_chain'
CHAIN = 'chain'

